export const EATERY_LIST_REQUEST = 'EATERY_LIST_REQUEST'
export const EATERY_LIST_SUCCESS = 'EATERY_LIST_SUCCESS'
export const EATERY_LIST_FAIL = 'EATERY_LIST_FAIL'

export const EATERY_DETAILS_REQUEST = 'EATERY_DETAILS_REQUEST'
export const EATERY_DETAILS_SUCCESS = 'EATERY_DETAILS_SUCCESS'
export const EATERY_DETAILS_FAIL = 'EATERY_DETAILS_FAIL'