export const EATERY_LIST_REQUEST = 'EATERY_LIST_REQUEST'
export const EATERY_LIST_SUCCESS = 'EATERY_LIST_SUCCESS'
export const EATERY_LIST_FAIL = 'EATERY_LIST_FAIL'

export const EATERY_DETAILS_REQUEST = 'EATERY_DETAILS_REQUEST'
export const EATERY_DETAILS_SUCCESS = 'EATERY_DETAILS_SUCCESS'
export const EATERY_DETAILS_FAIL = 'EATERY_DETAILS_FAIL'

export const EATERY_REVIEWS_REQUEST = 'EATERY_REVIEWS_REQUEST'
export const EATERY_REVIEWS_SUCCESS = 'EATERY_REVIEWS_SUCCESS'
export const EATERY_REVIEWS_FAIL = 'EATERY_REVIEWS_FAIL'


export const EATERY_DELETE_REQUEST = 'EATERY_DELETE_REQUEST'
export const EATERY_DELETE_SUCCESS = 'EATERY_DELETE_SUCCESS'
export const EATERY_DELETE_FAIL = 'EATERY_DELETE_FAIL'

export const EATERY_CREATE_REQUEST = 'EATERY_CREATE_REQUEST'
export const EATERY_CREATE_SUCCESS = 'EATERY_CREATE_SUCCESS'
export const EATERY_CREATE_FAIL = 'EATERY_CREATE_FAIL'
export const EATERY_CREATE_RESET = 'EATERY_CREATE_RESET'

export const EATERY_UPDATE_REQUEST = 'EATERY_UPDATE_REQUEST'
export const EATERY_UPDATE_SUCCESS = 'EATERY_UPDATE_SUCCESS'
export const EATERY_UPDATE_FAIL = 'EATERY_UPDATE_FAIL'
export const EATERY_UPDATE_RESET = 'EATERY_UPDATE_RESET'